export const ScreenName = {
  Splash: 'Splash',
  Onboarding: 'Onboarding',
  LocationService: 'LocationService',
  Login: 'Login',
  //DRAWER
  Drawer: 'Drawer',
  DashBoard: 'DashBoard',
  MyProfile: 'My Profile',
  LoanStatus: 'LoanStatus',
  EmiCalculation: 'EMI Calculator',
  ManDateDetails: 'Mandate Details',
  AdvanceEmi: 'Advance EMI',
  ForeCloseLoan: 'Foreclose Loan',
  EmiHolidays: 'EMI Holidays',
  GetInTouch: 'Get in Touch',
  ApplyNewLoan: 'Apply New Loans',
  PayOverDue: 'PayOverDue',
  PartPayment: 'PartPayment',
  MyLoan: 'MyLoan',
  PdfView: 'PdfViewer',
  Notification : 'Notification',
  Faq : 'Faq',
  Privacy : 'Privacy Policy',
  TRd : 'Terms of Service',
  Fpd : 'Fair Practice Code',
  CC : 'Citizen Charter',
  AboutUs : 'About Us',
  RepaymentShedual : 'RepaymentShedual',
  PaymentUI : 'PaymentUI',
};
