export const ScreenName = {
  Splash: 'Splash',
  Onboarding: 'Onboarding',
  LocationService: 'LocationService',
  Login: 'Login',
  //DRAWER
  Drawer: 'Drawer',
  DashBoard: 'DashBoard',
  MyProfile: 'My Profile',
  LoanStatus: 'LoanStatus',
  EmiCalculation: 'EMI Calculator',
  ManDateDetails: 'Mandate Details',
  AdvanceEmi: 'Advance EMI',
  ForeCloseLoan: 'Foreclose Loan',
  EmiHolidays: 'EMI Holidays',
  GetInTouch: 'Get in Touch',
  ApplyNewLoan: 'Apply New Loans',
  PayOverDue: 'PayOverDue',
  PartPayment: 'PartPayment',
  MyLoan: 'MyLoan',
};
