export default {
  SwadhaLogo: require('./images/SwadhaLogo.png'),
  Troffy: require('./images/Troffe.png'),
  OnbordingHalf1: require('./images/side1.png'),
  OnbordingRound: require('./images/circle.png'),
  OnbordingHalf2: require('./images/side2.png'),
  LoginTop: require('./images/login.png'),
  LogOut: require('./images/logout.png'),
  Menu: require('./images/menu.png'),
  arrow: require('./images/arrow.png'),
  calander: require('./images/calendar.png'),
  trd: require('./images/t&c.png'),
  profile: require('./images/profile.png'),
  notification: require('.//images/notification.png'),
  faq: require('./images/faq.png'),
  emi: require('./images/emi-icon.png'),
  contact: require('./images/contact.png'),
  citizen: require('./images/citizen-charter.png'),
  applyLoan: require('./images/apply-loan.png'),
  accountDetails: require('./images/account-details.png'),
  aboutUs: require('./images/about-us.png'),
  dashboard: require('./images/dashboard.png'),
};
